/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Conexion.ResultSetTableModel;
import Conexion.conexion;
import Controlador.DAO;
import Modelo.cliente;
import Modelo.usuario;

/**
 *
 * @author osvaldo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Inicio() {
        initComponents();
        ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
        jt_Altas.setModel(rst);
        jt_Bajas.setModel(rst);
        jt_Modificacion.setModel(rst);
        jt_Consultas.setModel(rst);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_altas = new javax.swing.JPanel();
        jsp_tablaDatos = new javax.swing.JScrollPane();
        jt_Altas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbl_IdClient = new javax.swing.JLabel();
        lbl_priAp = new javax.swing.JLabel();
        jtf_ap1 = new javax.swing.JTextField();
        lbl_preftype = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox<>();
        lbl_segunAp = new javax.swing.JLabel();
        jtf_ap2 = new javax.swing.JTextField();
        lbl_MaxRenta = new javax.swing.JLabel();
        jtf_renta = new javax.swing.JTextField();
        lbl_Telefono = new javax.swing.JLabel();
        jtf_tel = new javax.swing.JFormattedTextField();
        btn_agregar = new javax.swing.JButton();
        jt_idCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_IdClientBajas = new javax.swing.JLabel();
        lbl_priApBajas = new javax.swing.JLabel();
        jtf_apBajas = new javax.swing.JTextField();
        lbl_preftype1 = new javax.swing.JLabel();
        jcb_tipoBajas = new javax.swing.JComboBox<>();
        lbl_segunApBajas = new javax.swing.JLabel();
        jtf_ap2Bajas = new javax.swing.JTextField();
        lbl_MaxRenta1 = new javax.swing.JLabel();
        jtf_rentaBajas = new javax.swing.JTextField();
        lbl_TelefonoBajas = new javax.swing.JLabel();
        jtf_telBajas = new javax.swing.JFormattedTextField();
        btn_Bajas = new javax.swing.JButton();
        jtf_ID_Bajas = new javax.swing.JTextField();
        jsp_tablaDatos1 = new javax.swing.JScrollPane();
        jt_Bajas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_IdClientBajas1 = new javax.swing.JLabel();
        lbl_priApBajas1 = new javax.swing.JLabel();
        jtf_apModificacion = new javax.swing.JTextField();
        lbl_preftype2 = new javax.swing.JLabel();
        jcb_tipoModificacion = new javax.swing.JComboBox<>();
        lbl_segunApBajas1 = new javax.swing.JLabel();
        jtf_ap2Modificacion = new javax.swing.JTextField();
        lbl_MaxRenta2 = new javax.swing.JLabel();
        jtf_rentaModificacion = new javax.swing.JTextField();
        lbl_TelefonoBajas1 = new javax.swing.JLabel();
        jtf_telModificacion = new javax.swing.JFormattedTextField();
        btn_Modificacion = new javax.swing.JButton();
        jtf_ID_ClientModificacion = new javax.swing.JTextField();
        jsp_tablaDatos2 = new javax.swing.JScrollPane();
        jt_Modificacion = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_IdClientBajas2 = new javax.swing.JLabel();
        lbl_priApBajas2 = new javax.swing.JLabel();
        jtf_apBajas2 = new javax.swing.JTextField();
        lbl_preftype3 = new javax.swing.JLabel();
        jcb_tipoBajas2 = new javax.swing.JComboBox<>();
        lbl_segunApBajas2 = new javax.swing.JLabel();
        jtf_ap2Bajas2 = new javax.swing.JTextField();
        lbl_MaxRenta3 = new javax.swing.JLabel();
        jtf_rentaBajas2 = new javax.swing.JTextField();
        lbl_TelefonoBajas2 = new javax.swing.JLabel();
        jtf_telBajas2 = new javax.swing.JFormattedTextField();
        btn_Bajas2 = new javax.swing.JButton();
        jtf_ID_ClientModificacion1 = new javax.swing.JTextField();
        jsp_tablaDatos3 = new javax.swing.JScrollPane();
        jt_Consultas = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jTabbedPane1.setOpaque(true);
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jp_altas.setBackground(new java.awt.Color(235, 235, 235));

        jt_Altas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Altas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_Altas.setGridColor(new java.awt.Color(204, 204, 204));
        jsp_tablaDatos.setViewportView(jt_Altas);

        lbl_IdClient.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_IdClient.setText("ID_CLIENT");

        lbl_priAp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_priAp.setText("Nombre");

        jtf_ap1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ap1.setBorder(null);
        jtf_ap1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ap1KeyTyped(evt);
            }
        });

        lbl_preftype.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_preftype.setText("Tipo");

        jcb_tipo.setBackground(new java.awt.Color(235, 235, 235));
        jcb_tipo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Flat", "House" }));
        jcb_tipo.setBorder(null);
        jcb_tipo.setOpaque(false);

        lbl_segunAp.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_segunAp.setText("Apellido paterno");

        jtf_ap2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ap2.setBorder(null);
        jtf_ap2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ap2KeyTyped(evt);
            }
        });

        lbl_MaxRenta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_MaxRenta.setText("Maximo de Renta");

        jtf_renta.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_renta.setBorder(null);
        jtf_renta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_rentaKeyTyped(evt);
            }
        });

        lbl_Telefono.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_Telefono.setText("Telefono");

        jtf_tel.setBorder(null);
        jtf_tel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telActionPerformed(evt);
            }
        });
        jtf_tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_telKeyTyped(evt);
            }
        });

        btn_agregar.setBackground(new java.awt.Color(20, 111, 246));
        btn_agregar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setText("Agregar");
        btn_agregar.setBorder(null);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jt_idCliente.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_idCliente.setBorder(null);
        jt_idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_idClienteActionPerformed(evt);
            }
        });
        jt_idCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_idClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_IdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtf_ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_preftype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtf_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_MaxRenta, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jt_idCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_priAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(lbl_segunAp, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbl_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_IdClient)
                .addGap(4, 4, 4)
                .addComponent(jt_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_priAp)
                    .addComponent(lbl_segunAp)
                    .addComponent(lbl_Telefono))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_ap1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ap2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preftype)
                    .addComponent(lbl_MaxRenta))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_renta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jp_altasLayout = new javax.swing.GroupLayout(jp_altas);
        jp_altas.setLayout(jp_altasLayout);
        jp_altasLayout.setHorizontalGroup(
            jp_altasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_altasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_altasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsp_tablaDatos)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_altasLayout.setVerticalGroup(
            jp_altasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_altasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jsp_tablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Altas", jp_altas);

        lbl_IdClientBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_IdClientBajas.setText("ID_CLIENT");

        lbl_priApBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_priApBajas.setText("Nombre");

        jtf_apBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_apBajas.setBorder(null);
        jtf_apBajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_apBajasKeyTyped(evt);
            }
        });

        lbl_preftype1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_preftype1.setText("Tipo");

        jcb_tipoBajas.setBackground(new java.awt.Color(235, 235, 235));
        jcb_tipoBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jcb_tipoBajas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Flat", "House" }));
        jcb_tipoBajas.setBorder(null);
        jcb_tipoBajas.setOpaque(false);

        lbl_segunApBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_segunApBajas.setText("Apellido paterno");

        jtf_ap2Bajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ap2Bajas.setBorder(null);
        jtf_ap2Bajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ap2BajasKeyTyped(evt);
            }
        });

        lbl_MaxRenta1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_MaxRenta1.setText("Maximo de Renta");

        jtf_rentaBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_rentaBajas.setBorder(null);
        jtf_rentaBajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_rentaBajasKeyTyped(evt);
            }
        });

        lbl_TelefonoBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_TelefonoBajas.setText("Telefono");

        jtf_telBajas.setBorder(null);
        jtf_telBajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_telBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telBajasActionPerformed(evt);
            }
        });
        jtf_telBajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_telBajasKeyTyped(evt);
            }
        });

        btn_Bajas.setBackground(new java.awt.Color(20, 111, 246));
        btn_Bajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_Bajas.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bajas.setText("Eliminar");
        btn_Bajas.setBorder(null);
        btn_Bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BajasActionPerformed(evt);
            }
        });

        jtf_ID_Bajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ID_Bajas.setBorder(null);
        jtf_ID_Bajas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ID_BajasKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtf_apBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_ap2Bajas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_telBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_preftype1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_tipoBajas, 0, 170, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtf_rentaBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_MaxRenta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)
                        .addComponent(btn_Bajas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtf_ID_Bajas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_IdClientBajas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_priApBajas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(lbl_segunApBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbl_TelefonoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_IdClientBajas)
                .addGap(4, 4, 4)
                .addComponent(jtf_ID_Bajas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_priApBajas)
                    .addComponent(lbl_segunApBajas)
                    .addComponent(lbl_TelefonoBajas))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_apBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ap2Bajas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_telBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preftype1)
                    .addComponent(lbl_MaxRenta1))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_tipoBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_rentaBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Bajas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jt_Bajas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Bajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_Bajas.setGridColor(new java.awt.Color(204, 204, 204));
        jt_Bajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_BajasMouseClicked(evt);
            }
        });
        jsp_tablaDatos1.setViewportView(jt_Bajas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsp_tablaDatos1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jsp_tablaDatos1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bajas", jPanel2);

        lbl_IdClientBajas1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_IdClientBajas1.setText("ID_CLIENT");

        lbl_priApBajas1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_priApBajas1.setText("Nombre");

        jtf_apModificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_apModificacion.setBorder(null);
        jtf_apModificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_apModificacionKeyTyped(evt);
            }
        });

        lbl_preftype2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_preftype2.setText("Tipo");

        jcb_tipoModificacion.setBackground(new java.awt.Color(235, 235, 235));
        jcb_tipoModificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jcb_tipoModificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Flat", "House" }));
        jcb_tipoModificacion.setBorder(null);
        jcb_tipoModificacion.setOpaque(false);

        lbl_segunApBajas1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_segunApBajas1.setText("Apellido paterno");

        jtf_ap2Modificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ap2Modificacion.setBorder(null);
        jtf_ap2Modificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ap2ModificacionKeyTyped(evt);
            }
        });

        lbl_MaxRenta2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_MaxRenta2.setText("Maximo de Renta");

        jtf_rentaModificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_rentaModificacion.setBorder(null);
        jtf_rentaModificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_rentaModificacionKeyTyped(evt);
            }
        });

        lbl_TelefonoBajas1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_TelefonoBajas1.setText("Telefono");

        jtf_telModificacion.setBorder(null);
        jtf_telModificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_telModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telModificacionActionPerformed(evt);
            }
        });
        jtf_telModificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_telModificacionKeyTyped(evt);
            }
        });

        btn_Modificacion.setBackground(new java.awt.Color(20, 111, 246));
        btn_Modificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_Modificacion.setForeground(new java.awt.Color(255, 255, 255));
        btn_Modificacion.setText("Modificar");
        btn_Modificacion.setBorder(null);
        btn_Modificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificacionActionPerformed(evt);
            }
        });

        jtf_ID_ClientModificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ID_ClientModificacion.setBorder(null);
        jtf_ID_ClientModificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ID_ClientModificacionKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jtf_apModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_ap2Modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_telModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_preftype2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_tipoModificacion, 0, 170, Short.MAX_VALUE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtf_rentaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_MaxRenta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)
                        .addComponent(btn_Modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_IdClientBajas1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_priApBajas1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jtf_ID_ClientModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(lbl_segunApBajas1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbl_TelefonoBajas1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_IdClientBajas1)
                .addGap(4, 4, 4)
                .addComponent(jtf_ID_ClientModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_priApBajas1)
                    .addComponent(lbl_segunApBajas1)
                    .addComponent(lbl_TelefonoBajas1))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_apModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ap2Modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_telModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preftype2)
                    .addComponent(lbl_MaxRenta2))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_tipoModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_rentaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jt_Modificacion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Modificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_Modificacion.setGridColor(new java.awt.Color(204, 204, 204));
        jt_Modificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_ModificacionMouseClicked(evt);
            }
        });
        jsp_tablaDatos2.setViewportView(jt_Modificacion);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsp_tablaDatos2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jsp_tablaDatos2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificaciones", jPanel4);

        lbl_IdClientBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_IdClientBajas2.setText("ID_CLIENT");

        lbl_priApBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_priApBajas2.setText("Nombre");

        jtf_apBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_apBajas2.setBorder(null);
        jtf_apBajas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_apBajas2KeyTyped(evt);
            }
        });

        lbl_preftype3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_preftype3.setText("Tipo");

        jcb_tipoBajas2.setBackground(new java.awt.Color(235, 235, 235));
        jcb_tipoBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jcb_tipoBajas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "Flat", "House" }));
        jcb_tipoBajas2.setBorder(null);
        jcb_tipoBajas2.setOpaque(false);

        lbl_segunApBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_segunApBajas2.setText("Apellido paterno");

        jtf_ap2Bajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ap2Bajas2.setBorder(null);
        jtf_ap2Bajas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ap2Bajas2KeyTyped(evt);
            }
        });

        lbl_MaxRenta3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_MaxRenta3.setText("Maximo de Renta");

        jtf_rentaBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_rentaBajas2.setBorder(null);
        jtf_rentaBajas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_rentaBajas2KeyTyped(evt);
            }
        });

        lbl_TelefonoBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_TelefonoBajas2.setText("Telefono");

        jtf_telBajas2.setBorder(null);
        jtf_telBajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_telBajas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telBajas2ActionPerformed(evt);
            }
        });
        jtf_telBajas2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_telBajas2KeyTyped(evt);
            }
        });

        btn_Bajas2.setBackground(new java.awt.Color(20, 111, 246));
        btn_Bajas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btn_Bajas2.setForeground(new java.awt.Color(255, 255, 255));
        btn_Bajas2.setText("Buscar");
        btn_Bajas2.setBorder(null);
        btn_Bajas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Bajas2ActionPerformed(evt);
            }
        });

        jtf_ID_ClientModificacion1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_ID_ClientModificacion1.setBorder(null);
        jtf_ID_ClientModificacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_ID_ClientModificacion1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jtf_apBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_ap2Bajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jtf_telBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_preftype3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcb_tipoBajas2, 0, 170, Short.MAX_VALUE))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jtf_rentaBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_MaxRenta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)
                        .addComponent(btn_Bajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_IdClientBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_priApBajas2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jtf_ID_ClientModificacion1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addComponent(lbl_segunApBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbl_TelefonoBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lbl_IdClientBajas2)
                .addGap(4, 4, 4)
                .addComponent(jtf_ID_ClientModificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_priApBajas2)
                    .addComponent(lbl_segunApBajas2)
                    .addComponent(lbl_TelefonoBajas2))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_apBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_ap2Bajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_telBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_preftype3)
                    .addComponent(lbl_MaxRenta3))
                .addGap(4, 4, 4)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcb_tipoBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_rentaBajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Bajas2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jt_Consultas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Consultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jt_Consultas.setGridColor(new java.awt.Color(204, 204, 204));
        jsp_tablaDatos3.setViewportView(jt_Consultas);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsp_tablaDatos3)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jsp_tablaDatos3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultas", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telActionPerformed

    private void jtf_telBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telBajasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telBajasActionPerformed

    private void jtf_telModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telModificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telModificacionActionPerformed

    private void jtf_telBajas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telBajas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telBajas2ActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed

        String id = jt_idCliente.getText();
        String pa = jtf_ap1.getText();
        String sa = jtf_ap2.getText();
        String te = jtf_tel.getText();
        String ty = (String) jcb_tipo.getSelectedItem();
        String ax = jtf_renta.getText();
        if (id != "" && pa != "" && sa != "" && te != "" && ty != "Seleccione una opcion" && ax != "") {
            int ma = Integer.valueOf(jtf_renta.getText());
            // System.out.println("[id:"+id+"] [pa:"+pa+"] [sa:"+sa+"] [te:"+te+"] [ty:"+ty+"] [ma:"+ma+"]");
            cliente cl = new cliente(id, pa, sa, te, ty, ma);
            DAO da = new DAO(cl);

            if (da.altaCliente() == true) {
                System.out.println("Se agrego el Cliente out");

                jt_idCliente.setText("");
                jtf_ap1.setText("");
                jtf_ap2.setText("");
                jtf_tel.setText("");
                jcb_tipo.setSelectedIndex(0);
                jtf_renta.setText("");

                ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
                jt_Altas.setModel(rst);

            } else {
                System.err.println("No agrego el Cliente");
            }

        } else {
        }
        ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
        jt_Altas.setModel(rst); // Cargar tabla


    }//GEN-LAST:event_btn_agregarActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
        jt_Altas.setModel(rst); // Cargar tabla
        jt_Bajas.setModel(rst); 
        jt_Modificacion.setModel(rst); 
        jt_Consultas.setModel(rst); 
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void jt_idClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_idClienteKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas || numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jt_idClienteKeyTyped

    private void jtf_ap1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ap1KeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ap1KeyTyped

    private void jtf_ap2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ap2KeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ap2KeyTyped

    private void jt_idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_idClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_idClienteActionPerformed

    private void jtf_telKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_telKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
        if (jtf_tel.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_telKeyTyped

    private void jtf_rentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_rentaKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_rentaKeyTyped

    private void jtf_ID_BajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ID_BajasKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas || numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ID_BajasKeyTyped

    private void jtf_apBajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_apBajasKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_apBajasKeyTyped

    private void jtf_ap2BajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ap2BajasKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ap2BajasKeyTyped

    private void jtf_telBajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_telBajasKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
        if (jtf_tel.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_telBajasKeyTyped

    private void jtf_rentaBajasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_rentaBajasKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_rentaBajasKeyTyped

    private void jtf_ID_ClientModificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ID_ClientModificacionKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas || numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ID_ClientModificacionKeyTyped

    private void jtf_apModificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_apModificacionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_apModificacionKeyTyped

    private void jtf_ap2ModificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ap2ModificacionKeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ap2ModificacionKeyTyped

    private void jtf_telModificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_telModificacionKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_telModificacionKeyTyped

    private void jtf_rentaModificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_rentaModificacionKeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_rentaModificacionKeyTyped

    private void jtf_ID_ClientModificacion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ID_ClientModificacion1KeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas || numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ID_ClientModificacion1KeyTyped

    private void jtf_apBajas2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_apBajas2KeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_apBajas2KeyTyped

    private void jtf_ap2Bajas2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_ap2Bajas2KeyTyped
        int key = evt.getKeyChar();
        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_ap2Bajas2KeyTyped

    private void jtf_telBajas2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_telBajas2KeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_telBajas2KeyTyped

    private void jtf_rentaBajas2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_rentaBajas2KeyTyped
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!(numeros)) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf_rentaBajas2KeyTyped

    private void btn_Bajas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Bajas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Bajas2ActionPerformed

    private void jt_BajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_BajasMouseClicked
        String id = (String) jt_Bajas.getValueAt(jt_Bajas.getSelectedRow(), 0);
        String pa = (String) jt_Bajas.getValueAt(jt_Bajas.getSelectedRow(), 1);
        String sa = (String) jt_Bajas.getValueAt(jt_Bajas.getSelectedRow(), 2);
        String te = (String) jt_Bajas.getValueAt(jt_Bajas.getSelectedRow(), 3);
        Object ti = jt_Bajas.getValueAt(jt_Bajas.getSelectedRow(), 4);
        Object re = jt_Bajas.getValueAt(jt_Bajas.getSelectedRow(), 5);

        jtf_ID_Bajas.setText(id);
        jtf_apBajas.setText(pa);
        jtf_ap2Bajas.setText(sa);
        jtf_telBajas.setText(te);
        jcb_tipoBajas.setSelectedItem(ti);
        jtf_rentaBajas.setText(re.toString());

        jtf_ID_Bajas.setEnabled(false);
        jtf_apBajas.setEnabled(false);
        jtf_ap2Bajas.setEnabled(false);
        jtf_telBajas.setEnabled(false);
        jcb_tipoBajas.setEnabled(false);
        jtf_rentaBajas.setEnabled(false);

        // System.out.println(id + "][" + pa + "][" + sa + "][" + te + "][" + ti + "][" + re);
    }//GEN-LAST:event_jt_BajasMouseClicked

    private void btn_BajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BajasActionPerformed
        String id = jtf_ID_Bajas.getText();
        String pa = jtf_apBajas.getText();
        String sa = jtf_ap2Bajas.getText();
        String te = jtf_telBajas.getText();
        String ty = (String) jcb_tipoBajas.getSelectedItem();
        String ax = jtf_rentaBajas.getText();

        if (id != "" && pa != "" && sa != "" && te != "" && ty != "Seleccione una opcion" && ax != "") {
            int ma = Integer.valueOf(jtf_rentaBajas.getText());
            // System.out.println("[id:"+id+"] [pa:"+pa+"] [sa:"+sa+"] [te:"+te+"] [ty:"+ty+"] [ma:"+ma+"]");
            cliente cl = new cliente(id, pa, sa, te, ty, ma);
            DAO da = new DAO(cl);

            if (da.bajaCliente() == true) {
                System.err.println("Se elimino el Cliente");

                jtf_ID_Bajas.setText("");
                jtf_apBajas.setText("");
                jtf_ap2Bajas.setText("");
                jtf_telBajas.setText("");
                jcb_tipoBajas.setSelectedIndex(0);
                jtf_rentaBajas.setText("");

                ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
                jt_Bajas.setModel(rst);

            } else {
                System.err.println("No elimino el Cliente");
            }

        } else {
        }

        ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
        jt_Bajas.setModel(rst);
    }//GEN-LAST:event_btn_BajasActionPerformed

    private void jt_ModificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_ModificacionMouseClicked
        String id = (String) jt_Modificacion.getValueAt(jt_Modificacion.getSelectedRow(), 0);
        String pa = (String) jt_Modificacion.getValueAt(jt_Modificacion.getSelectedRow(), 1);
        String sa = (String) jt_Modificacion.getValueAt(jt_Modificacion.getSelectedRow(), 2);
        String te = (String) jt_Modificacion.getValueAt(jt_Modificacion.getSelectedRow(), 3);
        Object ti = jt_Modificacion.getValueAt(jt_Modificacion.getSelectedRow(), 4);
        Object re = jt_Modificacion.getValueAt(jt_Modificacion.getSelectedRow(), 5);

        jtf_ID_ClientModificacion.setText(id);
        jtf_ID_ClientModificacion.setEnabled(false);
        jtf_apModificacion.setText(pa);
        jtf_ap2Modificacion.setText(sa);
        jtf_telModificacion.setText(te);
        jcb_tipoModificacion.setSelectedItem(ti);
        jtf_rentaModificacion.setText(re.toString());
    }//GEN-LAST:event_jt_ModificacionMouseClicked

    private void btn_ModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificacionActionPerformed
        String id = jtf_ID_ClientModificacion.getText();
        String pa = jtf_apModificacion.getText();
        String sa = jtf_ap2Modificacion.getText();
        String te = jtf_telModificacion.getText();
        String ty = (String) jcb_tipoModificacion.getSelectedItem();
        String ax = jtf_rentaModificacion.getText();

        if (id != "" && pa != "" && sa != "" && te != "" && ty != "Seleccione una opcion" && ax != "") {
            int ma = Integer.valueOf(jtf_rentaModificacion.getText());
            // System.out.println("[id:"+id+"] [pa:"+pa+"] [sa:"+sa+"] [te:"+te+"] [ty:"+ty+"] [ma:"+ma+"]");
            cliente cl = new cliente(id, pa, sa, te, ty, ma);
            DAO da = new DAO(cl);

            if (da.modifiCliente() == true) {
                System.err.println("Se modifico el Cliente");

                jtf_ID_ClientModificacion.setText("");
                jtf_apModificacion.setText("");
                jtf_ap2Modificacion.setText("");
                jtf_telModificacion.setText("");
                jcb_tipoModificacion.setSelectedIndex(0);
                jtf_rentaModificacion.setText("");

                ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
                jt_Modificacion.setModel(rst);

            } else {
                System.err.println("No se modifico el Cliente");
            }

        } else {
        }

        ResultSetTableModel rst = conexion.obtenerRegistros("Select * from client"); //sacar de la BD
        jt_Modificacion.setModel(rst);
    }//GEN-LAST:event_btn_ModificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bajas;
    private javax.swing.JButton btn_Bajas2;
    private javax.swing.JButton btn_Modificacion;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcb_tipo;
    private javax.swing.JComboBox<String> jcb_tipoBajas;
    private javax.swing.JComboBox<String> jcb_tipoBajas2;
    private javax.swing.JComboBox<String> jcb_tipoModificacion;
    private javax.swing.JPanel jp_altas;
    private javax.swing.JScrollPane jsp_tablaDatos;
    private javax.swing.JScrollPane jsp_tablaDatos1;
    private javax.swing.JScrollPane jsp_tablaDatos2;
    private javax.swing.JScrollPane jsp_tablaDatos3;
    private javax.swing.JTable jt_Altas;
    private javax.swing.JTable jt_Bajas;
    private javax.swing.JTable jt_Consultas;
    private javax.swing.JTable jt_Modificacion;
    private javax.swing.JTextField jt_idCliente;
    private javax.swing.JTextField jtf_ID_Bajas;
    private javax.swing.JTextField jtf_ID_ClientModificacion;
    private javax.swing.JTextField jtf_ID_ClientModificacion1;
    private javax.swing.JTextField jtf_ap1;
    private javax.swing.JTextField jtf_ap2;
    private javax.swing.JTextField jtf_ap2Bajas;
    private javax.swing.JTextField jtf_ap2Bajas2;
    private javax.swing.JTextField jtf_ap2Modificacion;
    private javax.swing.JTextField jtf_apBajas;
    private javax.swing.JTextField jtf_apBajas2;
    private javax.swing.JTextField jtf_apModificacion;
    private javax.swing.JTextField jtf_renta;
    private javax.swing.JTextField jtf_rentaBajas;
    private javax.swing.JTextField jtf_rentaBajas2;
    private javax.swing.JTextField jtf_rentaModificacion;
    private javax.swing.JFormattedTextField jtf_tel;
    private javax.swing.JFormattedTextField jtf_telBajas;
    private javax.swing.JFormattedTextField jtf_telBajas2;
    private javax.swing.JFormattedTextField jtf_telModificacion;
    private javax.swing.JLabel lbl_IdClient;
    private javax.swing.JLabel lbl_IdClientBajas;
    private javax.swing.JLabel lbl_IdClientBajas1;
    private javax.swing.JLabel lbl_IdClientBajas2;
    private javax.swing.JLabel lbl_MaxRenta;
    private javax.swing.JLabel lbl_MaxRenta1;
    private javax.swing.JLabel lbl_MaxRenta2;
    private javax.swing.JLabel lbl_MaxRenta3;
    private javax.swing.JLabel lbl_Telefono;
    private javax.swing.JLabel lbl_TelefonoBajas;
    private javax.swing.JLabel lbl_TelefonoBajas1;
    private javax.swing.JLabel lbl_TelefonoBajas2;
    private javax.swing.JLabel lbl_preftype;
    private javax.swing.JLabel lbl_preftype1;
    private javax.swing.JLabel lbl_preftype2;
    private javax.swing.JLabel lbl_preftype3;
    private javax.swing.JLabel lbl_priAp;
    private javax.swing.JLabel lbl_priApBajas;
    private javax.swing.JLabel lbl_priApBajas1;
    private javax.swing.JLabel lbl_priApBajas2;
    private javax.swing.JLabel lbl_segunAp;
    private javax.swing.JLabel lbl_segunApBajas;
    private javax.swing.JLabel lbl_segunApBajas1;
    private javax.swing.JLabel lbl_segunApBajas2;
    // End of variables declaration//GEN-END:variables
}
