/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author osvaldo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jp_altas = new javax.swing.JPanel();
        jsp_tablaDatos = new javax.swing.JScrollPane();
        jt_Altas = new javax.swing.JTable();
        jp_datosTabla = new javax.swing.JPanel();
        jtf_branchNo = new javax.swing.JTextField();
        lbl_branchNo = new javax.swing.JLabel();
        lbl_street = new javax.swing.JLabel();
        jtf_street = new javax.swing.JTextField();
        lbl_city = new javax.swing.JLabel();
        jtf_city = new javax.swing.JTextField();
        lbl_postcode = new javax.swing.JLabel();
        jtf_postcode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jsp_listaTablas = new javax.swing.JScrollPane();
        jl_tablas = new javax.swing.JList<>();
        lbl_nombreTabla = new javax.swing.JLabel();
        lbl_Tablas = new javax.swing.JLabel();
        jp_Bajas = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jtf_branchNo1 = new javax.swing.JTextField();
        lbl_branchNo1 = new javax.swing.JLabel();
        lbl_street1 = new javax.swing.JLabel();
        jtf_street1 = new javax.swing.JTextField();
        lbl_city1 = new javax.swing.JLabel();
        jtf_city1 = new javax.swing.JTextField();
        lbl_postcode1 = new javax.swing.JLabel();
        jtf_postcode1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_Altas1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jl_tablas1 = new javax.swing.JList<>();
        jp_modificacion = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jtf_branchNo2 = new javax.swing.JTextField();
        lbl_branchNo2 = new javax.swing.JLabel();
        lbl_street2 = new javax.swing.JLabel();
        jtf_street2 = new javax.swing.JTextField();
        lbl_city2 = new javax.swing.JLabel();
        jtf_city2 = new javax.swing.JTextField();
        lbl_postcode2 = new javax.swing.JLabel();
        jtf_postcode2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_Altas2 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_tablas2 = new javax.swing.JList<>();
        jp_consultas = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jtf_branchNo3 = new javax.swing.JTextField();
        lbl_branchNo3 = new javax.swing.JLabel();
        lbl_street3 = new javax.swing.JLabel();
        jtf_street3 = new javax.swing.JTextField();
        lbl_city3 = new javax.swing.JLabel();
        jtf_city3 = new javax.swing.JTextField();
        lbl_postcode3 = new javax.swing.JLabel();
        jtf_postcode3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        jt_Altas3 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        jl_tablas3 = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));

        jp_altas.setBackground(new java.awt.Color(255, 255, 255));

        jt_Altas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Altas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsp_tablaDatos.setViewportView(jt_Altas);

        jp_datosTabla.setBackground(new java.awt.Color(235, 235, 235));

        jtf_branchNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_branchNo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_branchNo.setText("BranchNo");
        lbl_branchNo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_street.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_street.setText("Street");
        lbl_street.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_street.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_city.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_city.setText("City");
        lbl_city.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_city.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_postcode.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_postcode.setText("Postcode");
        lbl_postcode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_postcode.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_postcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_postcodeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¡Registro realizado con exito!");

        jButton1.setBackground(new java.awt.Color(0, 120, 215));
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jl_tablas.setBackground(new java.awt.Color(235, 235, 235));
        jl_tablas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jl_tablas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Branch", "Staff", "Property For Rent", "Client", "Private Owner", "Viewing", "Registration" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jsp_listaTablas.setViewportView(jl_tablas);

        lbl_nombreTabla.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_nombreTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nombreTabla.setText("Tabla Branch");

        lbl_Tablas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_Tablas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tablas.setText("Tablas");

        javax.swing.GroupLayout jp_datosTablaLayout = new javax.swing.GroupLayout(jp_datosTabla);
        jp_datosTabla.setLayout(jp_datosTablaLayout);
        jp_datosTablaLayout.setHorizontalGroup(
            jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosTablaLayout.createSequentialGroup()
                        .addGroup(jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jp_datosTablaLayout.createSequentialGroup()
                                .addGroup(jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_branchNo)
                                    .addComponent(lbl_branchNo, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jtf_street)
                                    .addComponent(lbl_street, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_city)
                                    .addComponent(jtf_postcode)
                                    .addComponent(lbl_city, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_nombreTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addGroup(jp_datosTablaLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(68, 68, 68)))
                .addGroup(jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_Tablas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jsp_listaTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );
        jp_datosTablaLayout.setVerticalGroup(
            jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosTablaLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbl_nombreTabla)
                .addGap(13, 13, 13)
                .addGroup(jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_datosTablaLayout.createSequentialGroup()
                        .addComponent(lbl_branchNo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_branchNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_datosTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_datosTablaLayout.createSequentialGroup()
                                .addComponent(lbl_street)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_street, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_datosTablaLayout.createSequentialGroup()
                                .addComponent(lbl_postcode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_postcode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_datosTablaLayout.createSequentialGroup()
                        .addComponent(lbl_city)
                        .addGap(6, 6, 6)
                        .addComponent(jtf_city, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jsp_listaTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jp_altasLayout = new javax.swing.GroupLayout(jp_altas);
        jp_altas.setLayout(jp_altasLayout);
        jp_altasLayout.setHorizontalGroup(
            jp_altasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_altasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_altasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsp_tablaDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addComponent(jp_datosTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_altasLayout.setVerticalGroup(
            jp_altasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_altasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_datosTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jsp_tablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Altas", jp_altas);

        jtf_branchNo1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_branchNo1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_branchNo1.setText("BranchNo");
        lbl_branchNo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_street1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_street1.setText("Street");
        lbl_street1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_street1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_city1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_city1.setText("City");
        lbl_city1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_city1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_postcode1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_postcode1.setText("Postcode");
        lbl_postcode1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_postcode1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_postcode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_postcode1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("¡Registro realizado con exito!");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_branchNo1)
                            .addComponent(jtf_street1)
                            .addComponent(lbl_street1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_branchNo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_city1)
                            .addComponent(jtf_postcode1)
                            .addComponent(lbl_city1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_postcode1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_branchNo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_branchNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_city1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_city1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_street1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_street1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbl_postcode1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_postcode1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jt_Altas1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Altas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jt_Altas1);

        jl_tablas1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jl_tablas1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Branch", "Staff", "Property For Rent", "Client", "Private Owner", "Viewing", "Registration" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jl_tablas1);

        javax.swing.GroupLayout jp_BajasLayout = new javax.swing.GroupLayout(jp_Bajas);
        jp_Bajas.setLayout(jp_BajasLayout);
        jp_BajasLayout.setHorizontalGroup(
            jp_BajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_BajasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_BajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(jp_BajasLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_BajasLayout.setVerticalGroup(
            jp_BajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BajasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_BajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bajas", jp_Bajas);

        jtf_branchNo2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_branchNo2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_branchNo2.setText("BranchNo");
        lbl_branchNo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_street2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_street2.setText("Street");
        lbl_street2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_street2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_city2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_city2.setText("City");
        lbl_city2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_city2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_postcode2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_postcode2.setText("Postcode");
        lbl_postcode2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_postcode2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_postcode2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_postcode2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("¡Registro realizado con exito!");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_branchNo2)
                            .addComponent(jtf_street2)
                            .addComponent(lbl_street2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_branchNo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_city2)
                            .addComponent(jtf_postcode2)
                            .addComponent(lbl_city2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_postcode2, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lbl_branchNo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_branchNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lbl_city2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_city2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lbl_street2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_street2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(lbl_postcode2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_postcode2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jt_Altas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Altas2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jt_Altas2);

        jl_tablas2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jl_tablas2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Branch", "Staff", "Property For Rent", "Client", "Private Owner", "Viewing", "Registration" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jl_tablas2);

        javax.swing.GroupLayout jp_modificacionLayout = new javax.swing.GroupLayout(jp_modificacion);
        jp_modificacion.setLayout(jp_modificacionLayout);
        jp_modificacionLayout.setHorizontalGroup(
            jp_modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_modificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(jp_modificacionLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_modificacionLayout.setVerticalGroup(
            jp_modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_modificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_modificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modificaciones", jp_modificacion);

        jtf_branchNo3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_branchNo3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_branchNo3.setText("BranchNo");
        lbl_branchNo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_street3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_street3.setText("Street");
        lbl_street3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_street3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_city3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_city3.setText("City");
        lbl_city3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_city3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        lbl_postcode3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_postcode3.setText("Postcode");
        lbl_postcode3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtf_postcode3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jtf_postcode3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_postcode3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setText("¡Registro realizado con exito!");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_branchNo3)
                            .addComponent(jtf_street3)
                            .addComponent(lbl_street3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_branchNo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_city3)
                            .addComponent(jtf_postcode3)
                            .addComponent(lbl_city3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_postcode3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lbl_branchNo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_branchNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lbl_city3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_city3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lbl_street3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_street3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(lbl_postcode3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_postcode3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jt_Altas3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jt_Altas3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jt_Altas3);

        jl_tablas3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jl_tablas3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Branch", "Staff", "Property For Rent", "Client", "Private Owner", "Viewing", "Registration" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane9.setViewportView(jl_tablas3);

        javax.swing.GroupLayout jp_consultasLayout = new javax.swing.GroupLayout(jp_consultas);
        jp_consultas.setLayout(jp_consultasLayout);
        jp_consultasLayout.setHorizontalGroup(
            jp_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_consultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .addGroup(jp_consultasLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_consultasLayout.setVerticalGroup(
            jp_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_consultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_consultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultas", jp_consultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_postcode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_postcode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_postcode1ActionPerformed

    private void jtf_postcode2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_postcode2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_postcode2ActionPerformed

    private void jtf_postcode3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_postcode3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_postcode3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtf_postcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_postcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_postcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> jl_tablas;
    private javax.swing.JList<String> jl_tablas1;
    private javax.swing.JList<String> jl_tablas2;
    private javax.swing.JList<String> jl_tablas3;
    private javax.swing.JPanel jp_Bajas;
    private javax.swing.JPanel jp_altas;
    private javax.swing.JPanel jp_consultas;
    private javax.swing.JPanel jp_datosTabla;
    private javax.swing.JPanel jp_modificacion;
    private javax.swing.JScrollPane jsp_listaTablas;
    private javax.swing.JScrollPane jsp_tablaDatos;
    private javax.swing.JTable jt_Altas;
    private javax.swing.JTable jt_Altas1;
    private javax.swing.JTable jt_Altas2;
    private javax.swing.JTable jt_Altas3;
    private javax.swing.JTextField jtf_branchNo;
    private javax.swing.JTextField jtf_branchNo1;
    private javax.swing.JTextField jtf_branchNo2;
    private javax.swing.JTextField jtf_branchNo3;
    private javax.swing.JTextField jtf_city;
    private javax.swing.JTextField jtf_city1;
    private javax.swing.JTextField jtf_city2;
    private javax.swing.JTextField jtf_city3;
    private javax.swing.JTextField jtf_postcode;
    private javax.swing.JTextField jtf_postcode1;
    private javax.swing.JTextField jtf_postcode2;
    private javax.swing.JTextField jtf_postcode3;
    private javax.swing.JTextField jtf_street;
    private javax.swing.JTextField jtf_street1;
    private javax.swing.JTextField jtf_street2;
    private javax.swing.JTextField jtf_street3;
    private javax.swing.JLabel lbl_Tablas;
    private javax.swing.JLabel lbl_branchNo;
    private javax.swing.JLabel lbl_branchNo1;
    private javax.swing.JLabel lbl_branchNo2;
    private javax.swing.JLabel lbl_branchNo3;
    private javax.swing.JLabel lbl_city;
    private javax.swing.JLabel lbl_city1;
    private javax.swing.JLabel lbl_city2;
    private javax.swing.JLabel lbl_city3;
    private javax.swing.JLabel lbl_nombreTabla;
    private javax.swing.JLabel lbl_postcode;
    private javax.swing.JLabel lbl_postcode1;
    private javax.swing.JLabel lbl_postcode2;
    private javax.swing.JLabel lbl_postcode3;
    private javax.swing.JLabel lbl_street;
    private javax.swing.JLabel lbl_street1;
    private javax.swing.JLabel lbl_street2;
    private javax.swing.JLabel lbl_street3;
    // End of variables declaration//GEN-END:variables
}
